- name: Hello World Sample
  hosts: "ec2-13-233-166-67.ap-south-1.compute.amazonaws.com"  #, "ec2-13-233-36-231.ap-south-1.compute.amazonaws.com"
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
